### ISSUE TITLE
After compiling, it cannot be installed. Help, boss.

### ISSUE THREAD

**Issue by maryjeck** [Smoothstep/apple-gen-rs#4]
like this
![图片](https://github.com/Smoothstep/apple-gen-rs/assets/4252556/1f878d1c-6a5d-409e-8481-c25949955bba)

**Comment by Smoothstep** [comment]
You could try adding a pyproject.toml in the directory of apple_functions_py with this content
`
[tool.maturin]
compatibility = "linux"
`
Read here [Maturin](https://github.com/PyO3/maturin?tab=readme-ov-file#source-distribution)

**Comment by maryjeck** [comment]
Thank you, you are truly my savior

**Comment by maryjeck** [comment]
> You could try adding a pyproject.toml in the directory of apple_functions_py with this content `[tool.maturin] compatibility = "linux"` Read here [Maturin](https://github.com/PyO3/maturin?tab=readme-ov-file#source-distribution)

@Smoothstep Can you teach me how to use it? I use this to get a bytes string following the example
![图片](https://github.com/Smoothstep/apple-gen-rs/assets/4252556/464e860b-8da1-40e6-8fa2-6573e05d238f)
怎么用这个生成一个data.plist

**Comment by Smoothstep** [comment]
Your question is not related to this project.
